export class Customer {
    CustomerId:any=null
    CustomerName:any
    CustomerTypeId:any
    Email1:any
    Email2:any
    URL:any
    Phone1:any
    Phone2:any
    Address1:any
    Address2:any
    Address3:any
    StateId:any 
    CIN:any
    GSTIN:any
    PAN:any
    TAN_NO:any
    Fax:any
    Status:any=1
    PreviousStatus:any=null
}
